import type { PrecedentCase } from "./types";

export const seedPrecedents: PrecedentCase[] = [
  {
    caseNumber: "TRB-2025-001",
    amount: 250000,
    currency: "USD",
    country: "US",
    counterpartyType: "institution",
    counterpartyName: "Goldman Sachs",
    purpose: "treasury_transfer",
    chain: "monad",
    prosecutorArg: "High-value transfer to unverified counterparty wallet raises AML concerns. Counterparty wallet has less than 30 days of on-chain history.",
    defenseArg: "Counterparty is a registered broker-dealer with SEC. Transaction is within established treasury management policy limits.",
    riskAssessment: "Medium risk — counterparty verified but transaction size is in the upper quartile. Standard KYC/CDD checks passed.",
    authorizationCheck: "Initiator has Level 3 treasury authorization. Multi-sig threshold met (2/3 required for this amount).",
    votes: { identity: "approve", prosecutor: "reject", defense: "approve", risk: "approve", authorization: "approve" },
    verdict: "approved",
    reviewOpinion: "Despite prosecutor's AML concerns, the defense successfully demonstrated institutional standing and compliance history.",
    tags: ["treasury", "institutional", "high-value", "approved"],
    timestamp: 1704067200000,
  },
  {
    caseNumber: "TRB-2025-002",
    amount: 45000,
    currency: "USD",
    country: "CN",
    counterpartyType: "vendor",
    counterpartyName: "Shenzhen Tech Corp",
    purpose: "ai_procurement",
    chain: "monad",
    prosecutorArg: "Payment to entity in sanctioned adjacent jurisdiction. Vendor not in approved supplier registry. No prior relationship.",
    defenseArg: "Vendor is a qualified AI hardware supplier with verified export licenses. Competitive pricing saves 18% versus domestic alternatives.",
    riskAssessment: "High risk — jurisdiction proximity to sanctioned regions, first-time vendor, technology goods classification triggers ECCN review.",
    authorizationCheck: "Initiator lacks cross-border procurement authorization. Requires Level 4+ for international technology purchases.",
    votes: { identity: "approve", prosecutor: "reject", defense: "approve", risk: "reject", authorization: "reject" },
    verdict: "blocked",
    reviewOpinion: "Transaction blocked due to combined risk and authorization failures. Cross-border technology procurement requires enhanced due diligence.",
    tags: ["procurement", "international", "technology", "blocked"],
    timestamp: 1704153600000,
  },
  {
    caseNumber: "TRB-2025-003",
    amount: 1200000,
    currency: "USD",
    country: "CH",
    counterpartyType: "institution",
    counterpartyName: "UBS AG",
    purpose: "treasury_transfer",
    chain: "monad",
    prosecutorArg: "Transaction exceeds single-transfer limit of $1M. Requires board-level approval which has not been documented.",
    defenseArg: "Transfer is part of quarterly rebalancing approved by the investment committee. Documentation pending upload.",
    riskAssessment: "Low risk — Swiss banking counterparty with AAA rating. Transaction within institutional treasury norms.",
    authorizationCheck: "Board approval required for amounts over $1M. Current authorization level insufficient.",
    votes: { identity: "approve", prosecutor: "reject", defense: "approve", risk: "approve", authorization: "reject" },
    verdict: "disputed",
    reviewOpinion: "Split decision referred to Review Judge. Authorization gap can be remedied by uploading board approval documentation. Recommend conditional approval upon document submission.",
    tags: ["treasury", "institutional", "high-value", "disputed", "conditional"],
    timestamp: 1704240000000,
  },
  {
    caseNumber: "TRB-2025-004",
    amount: 8900,
    currency: "USD",
    country: "DE",
    counterpartyType: "vendor",
    counterpartyName: "Munich Engineering GmbH",
    purpose: "supplier_payment",
    chain: "monad",
    prosecutorArg: "Invoice amount exceeds quoted estimate by 12%. No change order documentation provided.",
    defenseArg: "Overrun is within the 15% variance allowance per procurement policy. Work was completed ahead of schedule.",
    riskAssessment: "Low risk — established vendor with 3-year history, 47 prior invoices, all within policy tolerances.",
    authorizationCheck: "Standard Level 2 authorization for supplier payments under $10K. All approvals in place.",
    votes: { identity: "approve", prosecutor: "approve", defense: "approve", risk: "approve", authorization: "approve" },
    verdict: "approved",
    reviewOpinion: "Unanimous approval. Minor cost overrun within policy limits. Vendor performance history supports payment.",
    tags: ["supplier", "low-value", "approved", "repeat-vendor"],
    timestamp: 1704326400000,
  },
  {
    caseNumber: "TRB-2025-005",
    amount: 675000,
    currency: "USD",
    country: "AE",
    counterpartyType: "vendor",
    counterpartyName: "Dubai Digital Assets FZE",
    purpose: "ai_procurement",
    chain: "monad",
    prosecutorArg: "Counterparty operates in a digital asset free zone with limited regulatory oversight. Purpose code 'ai_procurement' does not match vendor's registered business activity.",
    defenseArg: "Vendor is licensed by Dubai Virtual Assets Regulatory Authority. Transaction is for GPU compute infrastructure, properly classified as AI procurement.",
    riskAssessment: "Elevated risk — jurisdiction flagged for enhanced monitoring. Vendor verification incomplete — missing beneficial ownership documentation.",
    authorizationCheck: "Initiator has Level 4 authorization. Transaction flagged for enhanced review due to jurisdiction risk profile.",
    votes: { identity: "approve", prosecutor: "reject", defense: "approve", risk: "reject", authorization: "approve" },
    verdict: "disputed",
    reviewOpinion: "The Review Judge finds the risk agent's concerns about jurisdiction and beneficial ownership well-founded. Transaction requires completion of enhanced due diligence before resubmission.",
    tags: ["procurement", "international", "high-risk-jurisdiction", "disputed"],
    timestamp: 1704412800000,
  },
];

